Desktop version Using media queries
MICHAELMUNAVU83/portfolio-mobile pull request #5
Opened 2022-02-16 19:16 UTC by MICHAELMUNAVU83

-Using media queries, I configured the desktop version of the portfolio.
- I used grid and flexbox to place elements correctly.
-

2022-02-16 20:42 UTC, Wes-Isaac requested changes
Hi @MICHAELMUNAVU83, @BasitKorede, 

Impressive work so far! 
There are some issues that you still need to work on to go to the next project but you are almost there!

### 📝👌 Your project highlights 🔥😎

- Linters are on point ✔
- Splendid work with the README file 👀
- Proper use of GitHub flow 👌

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
n/a

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-16 20:42 UTC, Wes-Isaac commented on style.css
> +    height: 800px;
- [ ] Great job implementing media query, however, there is a small gap before the body which is not according to the style, please fix that.
- [ ] In the desktop version there shouldn't be a hamburger menu, Please make sure that it's not displayed in the desktop version.
- [ ] Please follow the spacing provided in the figma design in the navbar at the end there are overlapping elements and also the postal icon is not there please fix it.

### Your implementation

![image](https://user-images.githubusercontent.com/59416136/154345713-2ddeaaa5-fd30-4a50-bbf8-0bb10cd7da43.png)

## Figma's design
![image](https://user-images.githubusercontent.com/59416136/154345953-5ab46523-c8ce-42ba-80bf-654f6ebfe380.png)

2022-02-16 20:42 UTC, Wes-Isaac commented on style.css
> +  }
- [ ] This block is moving up and down when the vertical length is varied. Kindly give it a proper position specified in the design.

### Your implementation

![image](https://user-images.githubusercontent.com/59416136/154349570-fa3a456b-45cb-4c40-95a5-41808c69f82e.png)

2022-02-16 20:42 UTC, Wes-Isaac commented on index.html
> +      <div class=""><img src="pics/image1.png" alt=""></div>
- [ ] This part is missing some things from the design for the desktop version. Kindly fix that.
- [ ] Please make sure you're using the same font.

 ### Your implementation 

![image](https://user-images.githubusercontent.com/59416136/154350304-5528c7fc-70ca-45e3-91ee-9140a5cba331.png)

### Figma's Design

![image](https://user-images.githubusercontent.com/59416136/154350377-43f73bd7-a0f2-49db-bd77-7532e8f931bc.png)

2022-02-16 20:42 UTC, Wes-Isaac commented on style.css
> +  }
- [ ] Great job there are a few things missing, the image is moving up and down please fix the position of that image and Kindly use the same font, spacing for all elements specified in the design.

### Your implementation

![image](https://user-images.githubusercontent.com/59416136/154351969-431d3411-834a-41f0-9d09-298a3a9d1d53.png)

### Figma's Design
![image](https://user-images.githubusercontent.com/59416136/154352042-cf4e7e49-a302-42d2-a348-718c232bdddb.png)

2022-02-16 20:42 UTC, Wes-Isaac commented on style.css
> +  }
- [ ] Please mind the space(margin & padding) on the framework section, they are not similar to the design. Kindly fix that.

### Your implementation

![image](https://user-images.githubusercontent.com/59416136/154352431-470ca6dc-8c22-4a56-8720-7dcaf1f8c635.png)

### Figma's Design
![image](https://user-images.githubusercontent.com/59416136/154352497-a87e96fa-6bf2-4da5-921c-42f3d6c9bd1c.png)

2022-02-16 20:42 UTC, Wes-Isaac commented on style.css
>  }
- [ ] While you have made a great effort positioning this element, the image is broken for the mobile version.

### Your implementation

![image](https://user-images.githubusercontent.com/59416136/154353194-f90bb3a2-9b76-4e40-bc8e-08d3e08c99ff.png)

### Figma's Design
![image](https://user-images.githubusercontent.com/59416136/154353302-dad96504-c263-49cd-b048-7daf77fb3e9f.png)

2022-02-17 16:07 UTC, nicupop729 commented on style.css
> +  }
**Here is what the figma template looks like:**
![image](https://user-images.githubusercontent.com/83596135/154521038-6936a481-b414-487f-8fcf-91d01afdccca.png)

**And here is what your project section looks like:**  
![image](https://user-images.githubusercontent.com/83596135/154521174-c0b1d641-ea0d-489f-9ead-540f9e22ac76.png)

- [ ] Kindly address this design with better use of Flexbox or Grid.

- [ ]  And please arrange the technologies to be situated in the middle of the boxes, and not top left as they are in now

2022-02-17 16:09 UTC, nicupop729 commented on index.html
> +
- [ ] Please remove the empty lines from 301 to 306.

2022-02-18 11:35 UTC, AnselemOdims requested changes
### Hi @MICHAELMUNAVU83, 
Good job implementing some of the changes suggested by previous reviewers.
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Please also check inline comments under the review

## Optional suggestions
- [ ] As already suggested by previous reviewers, I would also like to suggest avoiding using `position` to arrange elements(except in special occasions). It would be better to use `grid` and/or `flex` when positioning elements.

_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity!. Kindly tag me using @AnselemOdims for a quicker response or reach out to me on slack.

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-02-18 11:35 UTC, AnselemOdims commented on style.css
> +  }
- [ ] As already pointed out by the previous reviewer, please make sure your design adheres to the original design guidelines(fonts, colors, margins, padding etc). Kindly compare your design to the original design in [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471)
- [ ] As can be seen, yours is inverted. The list of technologies and the buttons do not align with the original design. Please implement these changes so your design can look identical to the design

### Your Design
![image](https://user-images.githubusercontent.com/43995830/154672257-e29eb95d-b70f-491f-898a-8ae728cf0754.png)

### Original Design
![image](https://user-images.githubusercontent.com/43995830/154672479-2fd9e334-aa44-4ace-b441-5cf4581b2981.png)

2022-02-18 11:35 UTC, AnselemOdims commented on style.css
> +}
- [ ] As already pointed out by the previous reviewer, please make sure the list of technologies (HTML, CSS, Ruby, JavaScript) on each project card aligns properly and sits in the middle of its box.

### Your Design
![image](https://user-images.githubusercontent.com/43995830/154673535-88c78e4c-7d94-4ab4-9bf7-4594f2115f26.png)

### Original Design
![image](https://user-images.githubusercontent.com/43995830/154673639-84f4e014-8a0e-488a-9f31-28a835023971.png)

2022-02-18 11:35 UTC, AnselemOdims commented on style.css
> +    margin-left: 30px;
- [ ] As stated earlier by the previous reviewers, kindly make sure the contact form matches the original design. At the moment, this is what it looks like 

### Your  Design
![image](https://user-images.githubusercontent.com/43995830/154674288-2fa53731-0d8b-463a-ad15-c80ec14bf285.png)

### Original Design
![image](https://user-images.githubusercontent.com/43995830/154674612-b57ef5d6-a395-45f6-83a4-5343e70295ae.png)

2022-02-22 10:50 UTC, merged